[package]
name = "deno_ts_example"
version = "0.0.1"
authors = ["Ryan Dahl <ry@tinyclouds.org>"]
edition = "2018"
publish = false

[dependencies]
deno = "0.15.0"

[build-dependencies]
deno_ts = { path = "../deno_ts" }

