[package]
name = "deno_snapshot"
version = "0.0.1"
authors = ["Ryan Dahl <ry@tinyclouds.org>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version="0.15.43", features=["full"] }
quote = "0.6.13"
deno = "0.14.0"
proc-macro2 = "0.4"

