[package]
name = "deno_cli_snapshots"
version = "0.0.1"
authors = ["Ryan Dahl <ry@tinyclouds.org>"]
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
deno = "0.15.0"

[build-dependencies]
deno_typescript = { path = "../deno_typescript" }

