[package]
name = "deno_ts"
publish = false
version = "0.15.0"
authors = ["Ryan Dahl <ry@tinyclouds.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
deno = "0.15.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
